name: Deploy QT6 WebAssembly Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Qt6 and WebAssembly tools
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-webengine-dev qt6-base-dev-tools qt6-webassembly

      - name: Build project for WebAssembly
        run: |
          mkdir build
          cd build
          /usr/lib/qt6/bin/qmake -spec wasm
          make

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build