name: Deploy QT6 WebAssembly Project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v11

      - name: Setup Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'
          host: 'linux'
          target: 'desktop'
          arch: 'wasm_32'
          tools: 'tools_webassembly'
          cache: true

      - name: Build project for WebAssembly
        run: |
          mkdir build && cd build
          qmake ../
          make

      - name: Prepare web files
        run: |
          mkdir -p web-build
          cp build/*.js web-build/
          cp build/*.wasm web-build/
          cp build/*.html web-build/
          # Create a simple index.html if it doesn't exist
          if [ ! -f web-build/index.html ]; then
            cp build/*.html web-build/index.html
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-build
          force_orphan: true
          user_name: "github-ci[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Publish to gh-pages"